### ISSUE TITLE
RSS and Feeds should be merged

### ISSUE THREAD

**Issue by WaylonWalker** [WaylonWalker/markata#25]
The existing rss plugin is quite rigid due to being one of the first plugins built into markata.  What would be really nice is to automatically make RSS feeds for each feed, with the option to turn off HTML or RSS.

## Example existing feeds config

The existing feeds plugin allows you to create feeds from a `filter`, `template`, and `card_template`

``` toml
[markata.feeds]
template="pages/templates/archive_template.html"
card_template="plugins/feed_card_template.html"

[markata.feeds.archive]
filter="date<=today and templateKey in ['blog-post', 'til'] and status.lower()=='published'"
[markata.feeds.blog]
filter="date<=today and templateKey in ['blog-post'] and status.lower()=='published'"
[markata.feeds.draft]
filter="status=='draft'"
```

After building you will end up with this kind of directory structure.

``` txt
├── markout
│   ├── 404.html
│   ├── archive
│   │       └── index.html
│   ├── blog
│   │       └── index.html
│   ├── draft
│   │       └── index.html
```

## Future state

Allow configurable turning RSS and HTML feeds on in configuration.

``` toml
[markata.feeds]
template="pages/templates/archive_template.html"
card_template="plugins/feed_card_template.html"
rss=true
html=true

[markata.feeds.archive]
filter="date<=today and templateKey in ['blog-post', 'til'] and status.lower()=='published'"
[markata.feeds.blog]
filter="date<=today and templateKey in ['blog-post'] and status.lower()=='published'"
html=false
[markata.feeds.draft]
filter="status=='draft'"
rss=false
```

``` txt
├── markout
│   ├── 404.html
│   ├── archive
│   │       ├── index.html
│   │       └── rss.xml
│   ├── blog
│   │       └── rss.xml
│   ├── draft
│   │       └── index.html
```
