### ISSUE TITLE
Automatically create feeds for tags

### ISSUE THREAD

**Issue by WaylonWalker** [WaylonWalker/markata#26]
Talking to [pypeaday](https://twitter.com/pypeaday), it seems confusing out of the box that markata does not create feeds for each tag.

I need to think through ideas on how to make this happen in configuration to make it generally useful.  You could make a custom hook on your own site to automate this, but generically inside markata its hard for me to know what keys will be in your front matter and what keys you want to create feeds for.

Here is some example configuration options.

``` toml
# proposed config, not real

[markata.feeds]
feed_for_each='tags'

[markata.feeds]
feed_for_each=['tags']
```
