### ISSUE TITLE
Markata site broken in GH Pages

### ISSUE THREAD

**Issue by pypeaday** [WaylonWalker/markata#57]
Routes seem to be broken in github pages...
![markata-broken](https://user-images.githubusercontent.com/32268273/185723567-c4a1fb19-218e-4b10-9e7f-33a7d6215e5c.png)

This is my small notes repo, https://github.com/pypeaday/small-group-notes, at commit 5b7d30d7b3745d8a7693b0cee1efb48bc13f1a19

Locally it's just running in docker-compose served up with python -m http.server.

In my markata.toml I have: url = "https://nicpayne713.github.io/small-group-notes/"

nicpayne713 forwards to pypeaday, I just hadn't updated my config yet but I don't think that's the problem

**Comment by pypeaday** [comment]
Did just confirm with the right url set in markata.toml the error remains

**Comment by WaylonWalker** [comment]
https://pypeaday.github.io/small-group-notes/bema/001-Trust-the-Story/

everything is deployed under https://pypeaday.github.io/small-group-notes, currently this is not configurable, but could be possible.  For now though you can change a few defaults to get it working.


You will need to explicitly add the 'archive' feed to point to the route defined.
https://markata.dev/markata/plugins/feeds/#card_template

``` toml
[markata.feeds.archive]
filter="True"
card_template="<li class='post'><a href='https://pypeaday.github.io/small-group-notes/{{ slug }}/'>{{ title }}</a></li>"
```

Then fix the links to your main.css to match the route. 

![image](https://user-images.githubusercontent.com/22648375/187054034-909542e7-09fd-4759-a1d0-494730e49a96.png)
